#!/usr/bin/env bash
# install-ativos-performance.sh
#
# Installs a CachyOS-inspired performance stack on top of AtivOS:
#   - zram compressed swap + tuned sysctl/udev settings
#   - ananicy-cpp (auto process priority) with an AtivOS rule set
#   - GameMode + MangoHud for gaming
#   - reflector (auto mirror ranking) for faster pacman downloads
#   - irqbalance, fstrim.timer, and the scx_loader sched_ext scheduler
#
# Safe to re-run: anything already installed/configured is left alone or
# simply overwritten with the same AtivOS defaults.
#
set -euo pipefail

if [[ $EUID -ne 0 ]]; then
    echo "Run with sudo: sudo ./install-ativos-performance.sh"
    exit 1
fi

if ! command -v pacman >/dev/null 2>&1; then
    echo "!! pacman not found — this script only supports Arch/AtivOS."
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FILES_DIR="$SCRIPT_DIR/files"

if [[ -t 1 ]]; then
    C_RESET='\033[0m'; C_BOLD='\033[1m'; C_DIM='\033[2m'
    C_ACCENT='\033[38;5;111m'; C_OK='\033[38;5;114m'; C_WARN='\033[38;5;179m'
else
    C_RESET=''; C_BOLD=''; C_DIM=''; C_ACCENT=''; C_OK=''; C_WARN=''
fi
info() { printf "${C_ACCENT}==>${C_RESET} %s\n" "$*"; }
ok()   { printf "${C_OK}  \xe2\x9c\x94${C_RESET} %s\n" "$*"; }
warn() { printf "${C_WARN}  !!${C_RESET} %s\n" "$*"; }

pkg_installed() { pacman -Qi "$1" >/dev/null 2>&1; }
multilib_enabled() { grep -qE '^\[multilib\]' /etc/pacman.conf 2>/dev/null; }

install_pkgs() {
    local todo=()
    for p in "$@"; do
        pkg_installed "$p" || todo+=("$p")
    done
    if [[ ${#todo[@]} -gt 0 ]]; then
        info "Installing: ${C_BOLD}${todo[*]}${C_RESET}"
        pacman -S --needed --noconfirm "${todo[@]}"
    else
        ok "Already installed: $*"
    fi
}

# A pacman transaction killed mid-flight can leave a stale lock file.
PACMAN_LOCK=/var/lib/pacman/db.lck
if [[ -f "$PACMAN_LOCK" ]] && ! pgrep -x pacman >/dev/null 2>&1; then
    info "Removing stale pacman lock ($PACMAN_LOCK, no pacman process running)"
    rm -f "$PACMAN_LOCK"
fi

# ---- 1. zram compressed swap -------------------------------------------
info "Setting up zram compressed swap"
install_pkgs zram-generator
install -Dm644 "$FILES_DIR/zram-generator.conf" /etc/systemd/zram-generator.conf
systemctl daemon-reload
# Zram is generated by a systemd generator, so it activates on the next
# boot automatically. Start it now too, so it's live immediately.
systemctl start systemd-zram-setup@zram0.service 2>/dev/null || \
    warn "Couldn't start zram0 immediately — it will still activate on next boot."
ok "zram configured"

# ---- 2. sysctl tuning ---------------------------------------------------
info "Applying sysctl performance tuning"
install -Dm644 "$FILES_DIR/99-ativos-performance.conf" /etc/sysctl.d/99-ativos-performance.conf
sysctl --system >/dev/null 2>&1 || warn "sysctl --system reported issues — check with: sudo sysctl --system"
ok "sysctl tuning installed"

# ---- 3. udev rules: I/O schedulers + zram swappiness --------------------
info "Installing I/O scheduler and zram udev rules"
install -Dm644 "$FILES_DIR/60-ativos-ioschedulers.rules" /etc/udev/rules.d/60-ativos-ioschedulers.rules
install -Dm644 "$FILES_DIR/61-ativos-zram-swap.rules"    /etc/udev/rules.d/61-ativos-zram-swap.rules
udevadm control --reload 2>/dev/null || true
udevadm trigger --subsystem-match=block 2>/dev/null || true
ok "udev rules installed"

# ---- 4. ananicy-cpp (auto process priority) ------------------------------
info "Setting up ananicy-cpp"
install_pkgs ananicy-cpp
mkdir -p /etc/ananicy.d
install -Dm644 "$FILES_DIR/00-ativos-types.rules" /etc/ananicy.d/00-ativos-types.rules
install -Dm644 "$FILES_DIR/10-ativos-rules.rules" /etc/ananicy.d/10-ativos-rules.rules
systemctl enable --now ananicy-cpp.service >/dev/null 2>&1 || \
    warn "Couldn't start ananicy-cpp.service — check: systemctl status ananicy-cpp"
ok "ananicy-cpp installed and enabled"

# ---- 5. GameMode + MangoHud ----------------------------------------------
info "Installing GameMode and MangoHud"
GAMEMODE_PKGS=(gamemode mangohud)
if multilib_enabled; then
    GAMEMODE_PKGS+=(lib32-gamemode lib32-mangohud)
fi
install_pkgs "${GAMEMODE_PKGS[@]}"
install -Dm644 "$FILES_DIR/gamemode.ini" /etc/gamemode.ini
install -Dm644 "$FILES_DIR/MangoHud.conf" /etc/mangohud/MangoHud.conf
ok "GameMode ready — launch games with: gamemoderun %command% (Steam) or gamemoderun <game>"
ok "MangoHud ready — enable per-game with: mangohud %command% (Steam) or mangohud <game>"

# ---- 6. reflector (faster mirrors) --------------------------------------
info "Setting up reflector for automatic mirror ranking"
install_pkgs reflector
install -Dm644 "$FILES_DIR/ativos-reflector.conf" /etc/xdg/reflector/reflector.conf
systemctl enable --now reflector.timer >/dev/null 2>&1 || \
    warn "Couldn't enable reflector.timer — check: systemctl status reflector.timer"
info "Ranking mirrors now (this can take a moment)..."
if reflector @/etc/xdg/reflector/reflector.conf 2>/dev/null; then
    ok "Mirrorlist ranked by speed"
else
    warn "Initial mirror ranking failed (probably no network yet) — reflector.timer will retry later."
fi

# ---- 7. irqbalance --------------------------------------------------------
info "Setting up irqbalance"
install_pkgs irqbalance
systemctl enable --now irqbalance.service >/dev/null 2>&1 || \
    warn "Couldn't start irqbalance.service"
ok "irqbalance enabled"

# ---- 8. periodic SSD trim ------------------------------------------------
info "Enabling weekly fstrim"
systemctl enable --now fstrim.timer >/dev/null 2>&1 || warn "Couldn't enable fstrim.timer"
ok "fstrim.timer enabled"

# ---- 9. scx_loader (pluggable sched_ext scheduler) -----------------------
info "Setting up sched_ext (scx_loader) CPU scheduler"
install_pkgs scx-scheds scx-tools
install -Dm644 "$FILES_DIR/scx_loader.toml" /etc/scx_loader.toml
if [[ -d /sys/kernel/sched_ext ]]; then
    systemctl enable --now scx_loader.service >/dev/null 2>&1 || \
        warn "Couldn't start scx_loader.service — check: systemctl status scx_loader"
    ok "scx_loader enabled (default scheduler: scx_bpfland)"
else
    systemctl enable scx_loader.service >/dev/null 2>&1 || true
    warn "This kernel doesn't expose sched_ext — scx_loader is enabled but will only take effect on a kernel that supports it (Linux 6.12+)."
fi

echo ""
ok "Performance stack installed."
echo "   Reboot to fully apply zram, sysctl, and scheduler changes."
